CREATE TABLE `BOOK_AUD` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(11) NULL,
  `BOOK_ID` INT NOT NULL,
  `OLD_TITLE` VARCHAR(255) NULL,
  `NEW_TITLE` VARCHAR(255) NULL,
  `OLD_PUBYEAR` INT NULL,
  `NEW_PUBYEAR` INT NULL,
  `CREATED_AT` DATETIME NULL,
  PRIMARY KEY (`ID`));

DELIMITER $$

CREATE TRIGGER BOOK_DELETE AFTER CREATE ON BOOK
FOR EACH ROW
BEGIN
	INSERT INTO `BOOK_AUD` (`CREATED_AT`,`TYPE`,`BOOK_ID`, `NEW_TITLE`, `NEW_PUBYEAR`)
    VALUES (curtime(), "CREATE", NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR);
END $$
DELIMITER ;

DELIMITER $$

CREATE TRIGGER BOOK_DELETE AFTER UPDATE ON RENTS
FOR EACH ROW
BEGIN
	INSERT INTO `BOOK_AUD` (`EVENT_DATE`, `EVENT_TYPE`, `BOOK_ID`, `OLD_TITLE`, `NEW_TITLE`, `OLD_PUBYEAR`, `NEW_PUBYEAR`)
    VALUES (curtime(), "UPDATE", OLD.BOOK_ID, OLD.TITLE, NEW.TITLE, OLD.PUBYEAR, NEW.PUBYEAR);
END $$
DELIMITER ;

DELIMITER $$

CREATE TRIGGER BOOK_DELETE AFTER DELETE ON RENTS
FOR EACH ROW
BEGIN
	INSERT INTO `BOOK_AUD` (`CREATED_AT`,`TYPE`, BOOK_ID)
    VALUES (curtime(), "DELETE", OLD.BOOK_ID);
END $$
DELIMITER ;



CREATE TABLE `READER_AUD` (
  `id` INT UNSIGNED NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `READER_ID` VARCHAR(45) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  `OLD_FIRSTNAME` VARCHAR(45) NULL,
  `NEW_FIRSTNAME` VARCHAR(45) NULL,
  `OLD_LASTNAME` VARCHAR(45) NULL,
  `NEW_LASTNAME` VARCHAR(45) NULL,
  `OLD_PESELID` VARCHAR(45) NULL,
  `NEW_PESELID` VARCHAR(45) NULL,
  `OLD_VIP_LEVEL` VARCHAR(45) NULL,
  `NEW_VIP_LEVEL` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


DELIMITER $$

CREATE TRIGGER BOOK_DELETE AFTER CREATE ON READER
FOR EACH ROW
BEGIN
	INSERT INTO `READER_AUD` (`CREATED_AT`,`TYPE`,`READER_ID`, `NEW_FIRSTNAME`, `NEW_LASTNAME`, `OLD_PESELID`,`NEW_PESELID`, `OLD_VIP_LEVEL`, `NEW_VIP_LEVEL`)
    VALUES (curtime(), "CREATE", NEW.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, OLD.PESELID, NEW.PESELID, OLD.VIP_LEVEL NEW.VIP_LEVEL);
END $$
DELIMITER ;

DELIMITER $$

CREATE TRIGGER BOOK_DELETE AFTER UPDATE ON READER
FOR EACH ROW
BEGIN
	INSERT INTO `READER_AUD` (`CREATED_AT`,`TYPE`,`READER_ID`,`OLD_FIRSTNAME`, `NEW_FIRSTNAME`, `OLD_LASTNAME`,`NEW_LASTNAME`, `NEW_PESELID`, `NEW_VIP_LEVEL`)
    VALUES (curtime(), "CREATE", NEW.READER_ID,OLD.FIRSTNAME NEW.FIRSTNAME,OLD.LASTNAME, NEW.LASTNAME, NEW.PESELID, NEW.VIP_LEVEL);
END $$
DELIMITER ;

DELIMITER $$

CREATE TRIGGER BOOK_DELETE AFTER DELETE ON READER
FOR EACH ROW
BEGIN
	INSERT INTO `BOOK_AUD` (`CREATED_AT`,`TYPE`, READER_ID)
    VALUES (curtime(), "DELETE", OLD.READER_ID);
END $$
DELIMITER ;